[workspace]
resolver = "2"
members = [
    "crates/project-model",
    "crates/runtime-diagnostics",
    "crates/midi-engine",
    "crates/compute-runtime",
    "crates/dsp",
    "crates/session",
    "crates/audio-engine",
    "crates/audio-platform",
    "crates/command-bus",
    "crates/application",
    "crates/cli",
    "crates/ui-shell",
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-or-later"
version = "0.1.0"
