[package]
name = "estudio-daw-audio-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Linux audio backends for Estudio DAW"

[dependencies]
estudio-daw-audio-engine = { path = "../audio-engine" }
pipewire = { version = "0.10.1", features = ["v0_3_44"] }
thiserror = "2"
